name: Terraform Deploy con LocalStack

on:
  push:
    branches:
      - main  # o la rama que uses

jobs:
  terraform:
    name: Despliegue Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Clona el repositorio
        uses: actions/checkout@v3

      - name: Instala Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Init
        run: terraform init

      - name: Plan
        run: terraform plan

      - name: Apply
        run: terraform apply -auto-approve
